[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --baud=2000000 --partition-table=partitions.csv --flash-size 4mb"
linker = "xtensa-esp32s3-elf-gcc"

[env]
CC_xtensa_esp32s3_none_elf = "xtensa-esp32s3-elf-gcc"
CFLAGS_xtensa_esp32s3_none_elf = "-mlongcalls -mtext-section-literals"

[build]
target = "xtensa-esp32s3-none-elf"
rustflags = ["-C", "link-arg=-nostartfiles"]

[unstable]
build-std = ["core"]
